version: "3"
services:
  postgres:
    image: "postgres:12"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql:z
    environment:
      - "POSTGRES_USER=username"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=ndx_poll_test"
  redis:
    image: "redis:5"
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - ./.redis:/data:z
    ports:
      - "6479:6379"
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - ./.minio_test:/export:z
    environment:
      - "MINIO_ACCESS_KEY=TESTACCESS"
      - "MINIO_SECRET_KEY=TESTSECRET"
    command: server /export
